// src/ui/features/attack_lab/catalog/scenarios/iot/iotRiskProfileQuickPorts.ts
// Escenario IOT external: perfilado rapido (real) por puertos comunes + vendor/OUI; produce VERDICT/WHY/NEXT.

import type { AttackLabScenario } from "../../types";
import { isWindows } from "../_shared/platform";

const escapePsSingleQuoted = (value: string) => value.replace(/'/g, "''");

export const iotRiskProfileQuickPortsScenario: AttackLabScenario = {
  id: "iot_risk_profile_quick_ports",
  title: "IoT: Perfilado de riesgo (puertos comunes)",
  description:
    "Auditoria rapida (real): probe TCP a puertos IoT comunes (web/rtsp/telnet/mqtt) + vendor/OUI. Prioriza el siguiente paso sin hacer un escaneo completo.",
  mode: "external",
  category: "IOT",
  nextScenarioIds: ["device_http_headers"],
  isSupported: () => {
    if (!isWindows()) return { supported: false, reason: "Preset pensado para Windows. Usa modo CUSTOM en otros SO." };
    return { supported: true };
  },
  buildRequest: ({ device }) => {
    const ipSafe = escapePsSingleQuoted(device.ip);
    const vendorSafe = escapePsSingleQuoted((device.vendor || "").trim());
    const macSafe = escapePsSingleQuoted((device.mac || "").trim());

    const script = [
      "$ErrorActionPreference = 'Continue'",
      "$lang = $env:NETSENTINEL_UI_LANG",
      "if (-not $lang) { $lang = 'es' }",
      "function _T($k) {",
      "  switch ($lang) {",
      "    'ca' {",
      "      switch ($k) {",
      "        'banner' { return '=== PERFIL IOT: PORTS QUICK PROBE ===' }",
      "        'tcp' { return '== TCP PROBE ==' }",
      "        'whyVendor' { return 'Vendor/OUI associat a IoT: prioritzar hardening i segmentacio.' }",
      "        'whyTelnet' { return 'Telnet obert: superficie legacy (risc alt si hi ha credencials per defecte).' }",
      "        'whyRtsp' { return 'RTSP obert: cameres/streaming; comprova autenticacio i aillament.' }",
      "        'whyMqtt' { return 'MQTT obert: bus IoT; revisa auth/ACL i exposicio.' }",
      "        'whyWeb' { return 'Web UI detectada: executar HTTP Fingerprint per headers/auth/cookies.' }",
      "        'whyNoPorts' { return 'Cap port comu detectat (pot usar ports no estandards o estar filtrat).' }",
      "        'nextDeep' { return '- Si necessites inventari complet: executa Deep Audit (ports) sobre el target.' }",
      "        'nextHttp' { return '- Si hi ha Web UI: executa HTTP Fingerprint (HEAD) i revisa redirects/auth.' }",
      "        'nextSeg' { return '- Recomanat: segmentar IoT (VLAN/SSID) i bloquejar accés lateral.' }",
      "      }",
      "    }",
      "    'en' {",
      "      switch ($k) {",
      "        'banner' { return '=== IOT PROFILE: PORTS QUICK PROBE ===' }",
      "        'tcp' { return '== TCP PROBE ==' }",
      "        'whyVendor' { return 'Vendor/OUI commonly IoT: prioritize hardening and segmentation.' }",
      "        'whyTelnet' { return 'Telnet open: legacy surface (high risk with default creds).' }",
      "        'whyRtsp' { return 'RTSP open: cameras/streaming; verify authentication and isolation.' }",
      "        'whyMqtt' { return 'MQTT open: IoT bus; review auth/ACL and exposure.' }",
      "        'whyWeb' { return 'Web UI detected: run HTTP Fingerprint for headers/auth/cookies.' }",
      "        'whyNoPorts' { return 'No common ports detected (may use non-standard ports or be filtered).' }",
      "        'nextDeep' { return '- If you need full inventory: run Deep Audit (ports) on the target.' }",
      "        'nextHttp' { return '- If there is a Web UI: run HTTP Fingerprint (HEAD) and review redirects/auth.' }",
      "        'nextSeg' { return '- Recommended: segment IoT (VLAN/SSID) and block lateral access.' }",
      "      }",
      "    }",
      "    default {",
      "      switch ($k) {",
      "        'banner' { return '=== PERFIL IOT: PORTS QUICK PROBE ===' }",
      "        'tcp' { return '== TCP PROBE ==' }",
      "        'whyVendor' { return 'Vendor/OUI asociado a IoT: priorizar hardening y segmentacion.' }",
      "        'whyTelnet' { return 'Telnet abierto: superficie legacy (riesgo alto si hay credenciales por defecto).' }",
      "        'whyRtsp' { return 'RTSP abierto: camaras/streaming; comprueba autenticacion y aislamiento.' }",
      "        'whyMqtt' { return 'MQTT abierto: bus IoT; revisa auth/ACL y exposicion.' }",
      "        'whyWeb' { return 'Web UI detectada: ejecutar HTTP Fingerprint para headers/auth/cookies.' }",
      "        'whyNoPorts' { return 'Ningun puerto comun detectado (puede usar puertos no estandar o estar filtrado).' }",
      "        'nextDeep' { return '- Si necesitas inventario completo: ejecuta Deep Audit (puertos) sobre el target.' }",
      "        'nextHttp' { return '- Si hay Web UI: ejecuta HTTP Fingerprint (HEAD) y revisa redirects/auth.' }",
      "        'nextSeg' { return '- Recomendado: segmentar IoT (VLAN/SSID) y bloquear acceso lateral.' }",
      "      }",
      "    }",
      "  }",
      "  return $k",
      "}",
      `$targetIp = '${ipSafe}'`,
      `$vendor = '${vendorSafe}'`,
      `$mac = '${macSafe}'`,
      "Write-Output (_T 'banner')",
      "Write-Output ('TARGET_IP: ' + $targetIp)",
      "if ($vendor) { Write-Output ('VENDOR: ' + $vendor) }",
      "if ($mac) { Write-Output ('MAC: ' + $mac) }",
      "Write-Output ('TIMESTAMP: ' + (Get-Date).ToString('s'))",
      "Write-Output ''",
      "if (-not ([System.Net.IPAddress]::TryParse($targetIp, [ref]$null))) {",
      "  Write-Error ('Invalid IPv4: ' + $targetIp)",
      "  exit 2",
      "}",
      "",
      "function Test-TcpPort($ip, $port, $timeoutMs) {",
      "  try {",
      "    $client = New-Object System.Net.Sockets.TcpClient",
      "    $iar = $client.BeginConnect($ip, $port, $null, $null)",
      "    $ok = $iar.AsyncWaitHandle.WaitOne($timeoutMs, $false)",
      "    if (-not $ok) { $client.Close(); return $false }",
      "    $client.EndConnect($iar) | Out-Null",
      "    $client.Close()",
      "    return $true",
      "  } catch {",
      "    try { $client.Close() } catch {}",
      "    return $false",
      "  }",
      "}",
      "",
      "$ports = @(80, 81, 443, 554, 8000, 8080, 8443, 22, 23, 1883, 5000, 5001, 34567, 37777)",
      "$open = @()",
      "Write-Output (_T 'tcp')",
      "foreach ($p in $ports) {",
      "  $isOpen = Test-TcpPort $targetIp $p 450",
      "  if ($isOpen) { $open += $p }",
      "  $s = if ($isOpen) { 'OPEN' } else { 'CLOSED' }",
      "  Write-Output ('TCP ' + $p + ': ' + $s)",
      "}",
      "Write-Output ''",
      "",
      // Verdict
      "$verdict = 'OK'",
      "$reasons = @()",
      "$next = @()",
      "$hasWeb = ($open -contains 80) -or ($open -contains 443) -or ($open -contains 8080) -or ($open -contains 8443) -or ($open -contains 81)",
      "$hasRtsp = ($open -contains 554) -or ($open -contains 8000)",
      "$hasTelnet = ($open -contains 23)",
      "$hasMqtt = ($open -contains 1883)",
      "if ($vendor) { $reasons += (_T 'whyVendor') }",
      "if ($hasTelnet) { $verdict = 'WARN'; $reasons += (_T 'whyTelnet') }",
      "if ($hasRtsp) { $verdict = 'WARN'; $reasons += (_T 'whyRtsp') }",
      "if ($hasMqtt) { $verdict = 'WARN'; $reasons += (_T 'whyMqtt') }",
      "if ($hasWeb) { $reasons += (_T 'whyWeb'); $next += (_T 'nextHttp') }",
      "if ($open.Count -eq 0) { $verdict = 'WARN'; $reasons += (_T 'whyNoPorts') }",
      "$next += (_T 'nextSeg')",
      "$next += (_T 'nextDeep')",
      "",
      "Write-Output '== VERDICT =='",
      "Write-Output ('VERDICT: ' + $verdict)",
      "Write-Output 'WHY:'",
      "$reasons | ForEach-Object { Write-Output ('- ' + $_) }",
      "Write-Output ''",
      "Write-Output 'NEXT:'",
      "$next | ForEach-Object { Write-Output $_ }",
    ].join("\n");

    return {
      binaryPath: "powershell.exe",
      args: ["-NoProfile", "-Command", script],
      timeoutMs: 60000,
    };
  },
};
