// /src/shared/constants/channels.ts

export const IPC_CHANNELS = {
  NETWORK: {
    SCAN_START: 'NETWORK:SCAN_START',
    PING_DEVICE: 'NETWORK:PING_DEVICE',
    GET_HISTORY: 'NETWORK:GET_HISTORY',
  },
  SECURITY: {
    AUDIT_TARGET: 'SECURITY:AUDIT_TARGET',
    AUDIT_PROGRESS: 'SECURITY:AUDIT_PROGRESS', 
    JAM_TARGET: 'SECURITY:JAM_TARGET'
  },
  SYSTEM: {
    GET_VERSION: 'SYSTEM:GET_VERSION',
  }
} as const;

