// src/ui/features/attack_lab/catalog/scenarios/_shared/powershellNetBaseline.ts
// Builder de script PowerShell: baseline de conectividad (PTR + ping + tracert) con salida localizada (NETSENTINEL_UI_LANG).

const escapePsSingleQuoted = (value: string) => value.replace(/'/g, "''");

export const buildNetBaselinePs = (targetIpRaw: string): string => {
  const targetIp = escapePsSingleQuoted(targetIpRaw);

  // Importante: se devuelve un script inline (multiline) para evitar depender de ficheros externos
  // y mantener el escenario portable.
  return [
    "$ErrorActionPreference = 'Continue'",
    "$lang = $env:NETSENTINEL_UI_LANG",
    "if (-not $lang) { $lang = 'es' }",
    "function _T($k) {",
    "  switch ($lang) {",
    "    'ca' {",
    "      switch ($k) {",
    "        'banner' { return '=== BASELINE DE XARXA: PTR + PING + TRACERT ===' }",
    "        'invalidIp' { return 'IPv4 invalid: ' }",
    "        'dns' { return '== DNS (reverse) ==' }",
    "        'ping' { return '== PING (Test-Connection) ==' }",
    "        'tracert' { return '== TRACERT (max 12 hops) ==' }",
    "        'baselineOk' { return 'Baseline consistent: connectivitat LAN estable cap al target.' }",
    "        'pingFail' { return 'PING ha fallat (ICMP filtrat o host no respon). No concloent per TCP.' }",
    "        'tracertHopsPrefix' { return 'TRACERT amb ' }",
    "        'tracertHopsSuffix' { return ' hops: possible VPN/bridge/segmentacio.' }",
    "        'highLatencyPrefix' { return 'Latencia mitjana alta (' }",
    "        'highLatencySuffix' { return 'ms): WiFi saturat/bufferbloat/ruta inestable.' }",
    "        'nextPorts' { return '- Si vols saber \"que esta exposat\": executa un audit de ports TCP/serveis.' }",
    "        'nextHttp' { return '- Si es un router amb panell web: executa HTTP Fingerprint (HEAD) i revisa redirects/auth.' }",
    "      }",
    "    }",
    "    'en' {",
    "      switch ($k) {",
    "        'banner' { return '=== NET BASELINE: PTR + PING + TRACERT ===' }",
    "        'invalidIp' { return 'Invalid IPv4: ' }",
    "        'dns' { return '== DNS (reverse) ==' }",
    "        'ping' { return '== PING (Test-Connection) ==' }",
    "        'tracert' { return '== TRACERT (max 12 hops) ==' }",
    "        'baselineOk' { return 'Consistent baseline: stable LAN connectivity to target.' }",
    "        'pingFail' { return 'PING failed (ICMP filtered or host not responding). Not conclusive for TCP.' }",
    "        'tracertHopsPrefix' { return 'TRACERT with ' }",
    "        'tracertHopsSuffix' { return ' hops: possible VPN/bridge/segmentation.' }",
    "        'highLatencyPrefix' { return 'High average latency (' }",
    "        'highLatencySuffix' { return 'ms): congested WiFi/bufferbloat/unstable route.' }",
    "        'nextPorts' { return '- If you want to know \"what is exposed\": run a TCP ports/services audit.' }",
    "        'nextHttp' { return '- If it is a router with web UI: run HTTP Fingerprint (HEAD) and review redirects/auth.' }",
    "      }",
    "    }",
    "    default {",
    "      switch ($k) {",
    "        'banner' { return '=== NET BASELINE: PTR + PING + TRACERT ===' }",
    "        'invalidIp' { return 'IPv4 invalida: ' }",
    "        'dns' { return '== DNS (reverse) ==' }",
    "        'ping' { return '== PING (Test-Connection) ==' }",
    "        'tracert' { return '== TRACERT (max 12 hops) ==' }",
    "        'baselineOk' { return 'Baseline consistente: conectividad LAN estable hacia el target.' }",
    "        'pingFail' { return 'PING fallo (ICMP filtrado o host no responde). No concluyente para TCP.' }",
    "        'tracertHopsPrefix' { return 'TRACERT con ' }",
    "        'tracertHopsSuffix' { return ' hops: posible VPN/bridge/segmentacion.' }",
    "        'highLatencyPrefix' { return 'Latencia media alta (' }",
    "        'highLatencySuffix' { return 'ms): WiFi saturado/bufferbloat/ruta inestable.' }",
    "        'nextPorts' { return '- Si quieres saber \"que esta expuesto\": ejecuta un audit de puertos TCP/servicios.' }",
    "        'nextHttp' { return '- Si es un router con panel web: ejecuta HTTP Fingerprint (HEAD) y revisa redirects/auth.' }",
    "      }",
    "    }",
    "  }",
    "  return $k",
    "}",
    `$targetIp = '${targetIp}'`,
    "Write-Output (_T 'banner')",
    "Write-Output ('TARGET_IP: ' + $targetIp)",
    "Write-Output ('TIMESTAMP: ' + (Get-Date).ToString('s'))",
    "Write-Output ''",
    "$ipParsed = $null",
    "if (-not ([System.Net.IPAddress]::TryParse($targetIp, [ref]$ipParsed))) {",
    "  Write-Error ((_T 'invalidIp') + $targetIp)",
    "  exit 2",
    "}",
    "",
    // PTR
    "$ptrOk = $false",
    "$ptrValue = ''",
    "Write-Output (_T 'dns')",
    "try {",
    "  $ptrValue = Resolve-DnsName -ErrorAction Stop -Type PTR -Name $targetIp | Select-Object -First 1 -ExpandProperty NameHost",
    "  if ($ptrValue) {",
    "    $ptrOk = $true",
    "    Write-Output ('PTR: ' + $ptrValue)",
    "  } else {",
    "    Write-Output 'PTR: <none>'",
    "  }",
    "} catch {",
    "  Write-Output ('PTR: <error> ' + $_.Exception.Message)",
    "}",
    "Write-Output ''",
    "",
    // Ping
    "$pingOk = $false",
    "$avg = $null; $min = $null; $max = $null",
    "Write-Output (_T 'ping')",
    "try {",
    "  $p = Test-Connection -ComputerName $targetIp -Count 4 -ErrorAction Stop",
    "  $avg = [Math]::Round(($p | Measure-Object -Property ResponseTime -Average).Average, 2)",
    "  $min = ($p | Measure-Object -Property ResponseTime -Minimum).Minimum",
    "  $max = ($p | Measure-Object -Property ResponseTime -Maximum).Maximum",
    "  $pingOk = $true",
    "  Write-Output ('PING_OK: true | AVG_MS=' + $avg + ' MIN_MS=' + $min + ' MAX_MS=' + $max)",
    "  $p | Select-Object Address, ResponseTime, Status | Format-Table -AutoSize | Out-String -Width 180 | ForEach-Object { $_.TrimEnd() }",
    "} catch {",
    "  Write-Output ('PING_OK: false | ' + $_.Exception.Message)",
    "}",
    "Write-Output ''",
    "",
    // Tracert
    "$hopCount = 0",
    "Write-Output (_T 'tracert')",
    "try {",
    // `tracert` puede tardar mucho si ICMP TTL-exceeded esta filtrado.
    // Reducimos timeout por probe para que el escenario siempre llegue a VERDICT en un tiempo razonable.
    "  $t = tracert -d -h 12 -w 250 $targetIp",
    "  $t | ForEach-Object { $_.TrimEnd() }",
    "  $hopCount = ($t | Where-Object { $_ -match '^\\s*\\d+\\s' }).Count",
    "} catch {",
    "  Write-Output ('TRACERT_ERROR: ' + $_.Exception.Message)",
    "}",
    "Write-Output ''",
    "",
    // Verdict
    "$verdict = 'OK'",
    "$reasons = @()",
    "if (-not $pingOk) { $verdict = 'WARN'; $reasons += (_T 'pingFail') }",
    "if ($hopCount -gt 1) { $verdict = 'WARN'; $reasons += ((_T 'tracertHopsPrefix') + $hopCount + (_T 'tracertHopsSuffix')) }",
    "if ($pingOk -and $avg -ne $null -and $avg -gt 50) { $verdict = 'WARN'; $reasons += ((_T 'highLatencyPrefix') + $avg + (_T 'highLatencySuffix')) }",
    "Write-Output '== VERDICT =='",
    "Write-Output ('VERDICT: ' + $verdict)",
    "if ($reasons.Count -eq 0) { $reasons += (_T 'baselineOk') }",
    "Write-Output 'WHY:'",
    "$reasons | ForEach-Object { Write-Output ('- ' + $_) }",
    "Write-Output ''",
    "Write-Output 'NEXT:'",
    "Write-Output (_T 'nextPorts')",
    "Write-Output (_T 'nextHttp')",
  // Usamos script multilínea para soportar bloques `switch {}` sin romper sintaxis con `;`.
  ].join("\n");
};
